// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VendingMachine.SqlPersistence;

namespace VendingMachine.SqlPersistence.Migrations
{
    [DbContext(typeof(MachineContext))]
    [Migration("20210123181840_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("VendingMachine.Domain.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("VendingMachine.Domain.Piles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MachineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("SnackCapacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("Piles");
                });

            modelBuilder.Entity("VendingMachine.Domain.Snack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PilesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PilesId");

                    b.ToTable("Snack");
                });

            modelBuilder.Entity("VendingMachine.Domain.Piles", b =>
                {
                    b.HasOne("VendingMachine.Domain.Machine", null)
                        .WithMany("Piles")
                        .HasForeignKey("MachineId");
                });

            modelBuilder.Entity("VendingMachine.Domain.Snack", b =>
                {
                    b.HasOne("VendingMachine.Domain.Piles", null)
                        .WithMany("Snacks")
                        .HasForeignKey("PilesId");
                });

            modelBuilder.Entity("VendingMachine.Domain.Machine", b =>
                {
                    b.Navigation("Piles");
                });

            modelBuilder.Entity("VendingMachine.Domain.Piles", b =>
                {
                    b.Navigation("Snacks");
                });
#pragma warning restore 612, 618
        }
    }
}
